config/routes.rb
Rails.application.routes.draw do
  # use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homepage#index"

  get '/home/services', to: 'homepage#services'
  get '/users/logout', to: 'users#logout'
  
  namespace :patients do
    get '/login',  to: 'patients#login'
    get '/signup', to: 'patients#signup'
    post '/login', to: 'patients#authenticate'
    post '/signup', to: 'patients#create'
    get '/show', to: 'users#show'
  end

  namespace :clients do
    get '/login',  to: 'clients#login'
    get '/signup', to: 'clients#signup'
    post '/login', to: 'clients#authenticate'
    post '/signup', to: 'clients#create'
    get '/show', to: 'users#show'
  end

  get '/services', to: 'bookings#services'

  resources :users, only: [] do
    resources :bookings
  end

  resources :doctors, only: %i[index show]

  get '/payments', to: 'payments#new'
  post '/payments', to: 'payments#create'
  post '/payments/delete', to: 'payments#delete'

  resources :bookings, only: [] do
    get '/ambulances', to: 'ambulances#new'
    post '/ambulances', to: 'ambulances#create'
    delete '/ambulance/:id', to: 'ambulances#delete'

    get '/appointments', to: 'appointments#new'
    post '/appointments', to: 'appointments#create'
    delete '/appointments/:id', to: 'appointments#delete', as: 'appointments_delete'

    get '/lab_test', to: 'lab_tests#new'
    post '/lab_test', to: 'lab_tests#create'
    delete '/lab_test/:id', to: 'lab_tests#delete'
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  layout 'homepage'

  def index
    redirect_to user_bookings_path(current_user) and return if doorkeeper_token.present?

    @locations = Location::DEFAULT_ZIP_CODES
  end


  def services
    @location = Location.find_by(zip_code: zip_code)

    unless @location.present?
      flash[:error] = 'No services available or you need to register'
      render 'services' and return
    end

    @doctors = Doctor.at_locations(@location.id).take(5)
  end

  private
 
  def zip_code
    params[:location_id]
  end
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/homepage/index.html.erb
<div class="block md:hidden container mx-auto py-8 flex justify-center">
<% unless current_user %>
  <ul class="w-48 text-sm font-medium text-white">
    <li class="py-4 px-4 w-full rounded-lg bg-blue-700">
      <%= link_to "Patient Signup", patients_signup_url %>
    </li>

    <li class="py-4 px-4 w-full rounded-lg mt-5 bg-blue-700">
      <%= link_to "Patient Login", patients_login_url %>
    </li>
  </ul>
<% end %>
</div>

<div class="md:mt-10 py-5 md:py-20 pl-10">
  <div class="container mx-auto px-6">
    <%= image_tag('icon.png', alt: 'hero icon') %>
    <h2 class="text-4xl font-bold mb-2 text-black">
      Helping you with faster and easier medical services!
    </h2>
    <h3 class="text-2xl pt-4 mb-8 text-gray-400">
      Find doctors or book lab tests in few easy steps.
    </h3>
  </div>
</div>


<div class="py-20 text-center md:pl-10" style="background: linear-gradient(90deg, #667eea 0%, #0098b1 100%)">
  <div class="container px-6 mx-auto">
    <%= form_with(url: home_services_path, method: "get", class: "flex flex-row") do |f| %>
      <%= f.select :location_id, @locations.collect{ |u| [u.city, u.zip_code] }, {}, class: "w-8/12 bg-white text-xl rounded-lg", id: "selectCity", include_blank: 'Select city' %>
    <%= f.submit "Search", class: "bg-white font-bold rounded-lg ml-2 py-4 px-8 shadow-lg uppercase tracking-wider" %>
  <% end %>
  </div>
</div>

<section class="container mx-auto px-6 p-10">
  <h2 class="text-4xl font-bold text-center text-gray-800 mb-8">
    Features
  </h2>
  <div class="flex justify-evenly items-center flex-wrap mb-20">
    <div>
      <h4 class="text-3xl text-gray-800 font-bold mb-3">Easy Appointment Bookings</h4>
      <p class="text-gray-600 mb-8">Find doctors in your location and book instantly.</p>
    </div>
    <div>
      <%= image_tag("doctor.jpeg", alt: 'doctor') %>
    </div>
  </div>

  <div class="flex justify-evenly items-center flex-wrap mb-20">
    <div>
      <%= image_tag("labtest.jpeg", alt: 'lab test`') %>
    </div>
    <div>
      <h4 class="text-3xl text-gray-800 font-bold mb-3">Reporting</h4>
      <p class="text-gray-600 mb-8">Book lab tests easily</p>
    </div>
  </div>
</section>

app/views/homepage/services.html.erb
<div class="container mx-auto py-8 px-10">
  <h3 class="text-2xl pb-10">Doctors</h3>
  <div class="flow-root">
    <ul role="list" class="divide-y divide-gray-200 dark:divide-gray-700">
      <% @doctors.each do |doctor| %>
        <li class="py-3 sm:py-4">
          <div class="flex items-center space-x-4">
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium text-gray-900 truncate dark:text-white">
              <%= doctor.full_name %>
              </p>
              <p class="text-sm text-gray-500 truncate dark:text-gray-400">
              <%= doctor.specialities.map(&:name).join(", ") %>
              </p>
            </div>
            <div class="inline-flex items-center text-base font-semibold text-white dark:text-white">
              <%= link_to "Book", patients_login_url, class: "inline-block px-8 py-2 bg-blue-600" %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>