config/routes.rb
Rails.application.routes.draw do
  # use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homepage#index"

  get '/home/services', to: 'homepage#services'
  get '/users/logout', to: 'users#logout'
  
  namespace :patients do
    get '/login',  to: 'patients#login'
    get '/signup', to: 'patients#signup'
    post '/login', to: 'patients#authenticate'
    post '/signup', to: 'patients#create'
    get '/show', to: 'users#show'
  end

  namespace :clients do
    get '/login',  to: 'clients#login'
    get '/signup', to: 'clients#signup'
    post '/login', to: 'clients#authenticate'
    post '/signup', to: 'clients#create'
    get '/show', to: 'users#show'
  end

  get '/services', to: 'bookings#services'

  resources :users, only: [] do
    resources :bookings
  end

  resources :doctors, only: %i[index show]

  get '/payments', to: 'payments#new'
  post '/payments', to: 'payments#create'
  post '/payments/delete', to: 'payments#delete'

  resources :bookings, only: [] do
    get '/ambulances', to: 'ambulances#new'
    post '/ambulances', to: 'ambulances#create'
    delete '/ambulance/:id', to: 'ambulances#delete'

    get '/appointments', to: 'appointments#new'
    post '/appointments', to: 'appointments#create'
    delete '/appointments/:id', to: 'appointments#delete', as: 'appointments_delete'

    get '/lab_test', to: 'lab_tests#new'
    post '/lab_test', to: 'lab_tests#create'
    delete '/lab_test/:id', to: 'lab_tests#delete'
  end
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  has_secure_password
  attr_accessor :locations, :specialities

  validates :password, presence: true, on: :create
  # validates :name, :phone, :country_code, presence: true

  validates :country_code, numericality: {in: 0..999}, allow_blank: true
  validates_format_of :phone, :with => /[0-9]{10,}/, allow_blank: true

  validates :email, presence: true, uniqueness: true, format: { with: /\A[^@\s]+@[^@\s]+\z/ }
  validates :registration_number, presence: true, uniqueness: true

  before_save do
  end

  def self.at_locations(location_ids = [])
    where("location_ids LIKE '%?%'", location_ids)
  end

  def locations=(array = [])
    self.location_ids = serialize_array(array)
  end

  def specialities=(array = [])
    self.speciality_ids = serialize_array(array)
  end

  def locations 
    Location.where(id: location_ids.gsub(/[{}]/, '').split(','))
  end

  def specialities
    Speciality.where(id: speciality_ids.gsub(/[{}]/, '').split(','))
  end

  def full_name
    "#{salutation}, #{name}"
  end

  private

  def serialize_array(array)
    "{#{array.join(",")}}"
  end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :authenticate!

  def index
    @booking_id = params[:booking_id] || 3
    @location_ids = location_params[:locations].map(&:to_i)
    @doctors = Doctor.at_locations(@location_ids)
  end

  private

  def location_params
    params.permit(locations: []).with_defaults(locations: [])
  end
end

app/views/doctors/index.html.erb
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-4 gap-5">
  <% @doctors.each do |doctor| %>
    <div class="p-6 max-w-md bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700">
      <figure class="bg-slate-100 rounded-xl p-8 dark:bg-slate-800">
        <h3 class="pb-6"><%= doctor.salutation %>, <%= doctor.name %></h3>

        <%= link_to "Book now", booking_appointments_url(booking_id: encrypt_params(booking_id: @booking_id, doctor_id: doctor.id, location_id: @location_ids)), class:'bookdoctor inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800' %>

        <!-- Specialities -->
        <div class="font-medium grid grid-cols-none divide-x pt-6">
          <% doctor.specialities.each do |speciality| %>
            <div class="text-sky-500 dark:text-sky-400">
              <%= speciality.name %>
            </div>
          <% end %>
        </div>

      </figure>
    </div>
  <% end %>
</div>

<div class="fixed z-10 overflow-y-auto top-0 w-full left-0 hidden" id="modal"></div>