config/routes.rb
Rails.application.routes.draw do
  # use_doorkeeper
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root "homepage#index"

  get '/home/services', to: 'homepage#services'
  get '/users/logout', to: 'users#logout'
  
  namespace :patients do
    get '/login',  to: 'patients#login'
    get '/signup', to: 'patients#signup'
    post '/login', to: 'patients#authenticate'
    post '/signup', to: 'patients#create'
    get '/show', to: 'users#show'
  end

  namespace :clients do
    get '/login',  to: 'clients#login'
    get '/signup', to: 'clients#signup'
    post '/login', to: 'clients#authenticate'
    post '/signup', to: 'clients#create'
    get '/show', to: 'users#show'
  end

  get '/services', to: 'bookings#services'

  resources :users, only: [] do
    resources :bookings
  end

  resources :doctors, only: %i[index show]

  get '/payments', to: 'payments#new'
  post '/payments', to: 'payments#create'
  post '/payments/delete', to: 'payments#delete'

  resources :bookings, only: [] do
    get '/ambulances', to: 'ambulances#new'
    post '/ambulances', to: 'ambulances#create'
    delete '/ambulance/:id', to: 'ambulances#delete'

    get '/appointments', to: 'appointments#new'
    post '/appointments', to: 'appointments#create'
    delete '/appointments/:id', to: 'appointments#delete', as: 'appointments_delete'

    get '/lab_test', to: 'lab_tests#new'
    post '/lab_test', to: 'lab_tests#create'
    delete '/lab_test/:id', to: 'lab_tests#delete'
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :authenticate!

  def new
    @location_id = booking_info[:location_id]
    @doctor_id = booking_info[:doctor_id]
    @doctorslot = DoctorSlot.find_by(doctor_id: @doctor_id, location_id: @location_id)

    if @doctorslot.present?
      @available_slots = @doctorslot.available_slots
        .each_with_index.collect {|slot, i| [slot.join(' - '), i]}
        .filter { |t| t[0].present? }
    end

    return if @available_slots.present?

    flash[:error] = 'No avaiable slots'
    redirect_to doctors_url(booking_id: booking_info[:booking_id], locations: @location_id)
  end

  def create
    @doctorslot = DoctorSlot.find_by(doctor_id: booking_info[:doctor_id], location_id: booking_info[:location_id])
    expiry = DateTime.strptime(@doctorslot.slots[params[:slot_number].to_i][1], '%H:%M')

    begin
      bp = booking_info.merge({
        amount_to_pay: @doctorslot.amount_to_pay,
        expires_at: expiry,
        doctor_slot_id: @doctorslot.id,
        user_id: current_user.id,
        slot_number: params[:slot_number]
      })

      @order = AppointmentBooking.book!(bp.with_indifferent_access)
    rescue => err
      Rails.logger.error err
      flash[:error] = 'Slot Booking Failed. Please Retry!'
      redirect_to doctors_url(booking_id: 3, locations: [@doctorslot.location_id.to_s]) and return
    end

    begin
      @payment = Payment.create!(@order, @doctorslot)
    rescue => err
      Rails.logger.error err
      flash[:error] = 'Payment failed'
    rescue => err
      Rails.logger.error err
      flash[:error] = 'Something went wrong. Please contact ccu'
    end

    if flash[:error].present?
      redirect_to doctors_url(booking_id: 3, locations: [@doctorslot.location_id.to_s]) and return
    end

    redirect_to payments_url
  end

  def delete
    @appointment = AppointmentBooking.find(params[:id])
    if @appointment.user_id != current_user.id
      flash[:error] = 'Failed to cancel others booking.'
      redirect_to user_bookings_url(current_user.id) and return
    end

    begin
      @appointment.expire!
    rescue => e
      puts e
      flash[:error] = 'Failed to cancel booking. Please Retry!'
    else
      flash[:success] = 'Booking cancelled'
    end

    redirect_to user_bookings_url(current_user.id)
  end

  def update
  end

  private

  def booking_params
    params.permit(:slot_number, :booking_id)
  end

  def booking_info
    bid = decrypt_param(params[:booking_id])
    return {} unless bid.present?

    @booking_info ||= JSON.parse(bid).with_indifferent_access
  end

end

app/views/appointments/new.html.erb
<div class="flex justify-center">
  <%= form_with url: booking_appointments_path, method: 'post', class: 'bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4' do |f| %>
    <%= f.text_field :location_id, class: 'hidden', value: @location_id, readonly: true %>
    <%= f.text_field :doctor_id, class: 'hidden', value: @doctor_id, readonly: true %>
    <label>Doctor</label>
    <input type="text" class="w-full bg-gray-100 p-2 mt-2 mb-3" value="<%= @doctorslot.doctor.full_name %>" readonly />
    <label>Patient</label>
    <input type="text" class="w-full bg-gray-100 p-2 mt-2 mb-3" value="<%= current_user.name %>" readonly />
    <%= f.label :slot_number, "Select Slot" %>
    <%= f.select :slot_number, options_for_select(@available_slots), {}, class: "w-full bg-gray-100 p-2 mt-2 mb-3" %>
    <div class="py-3 text-right">
      <%= f.submit "Book", class: "py-2 px-4 bg-blue-500 text-white rounded hover:bg-blue-700 mr-2" %>
    </div>
  <% end %>
</div>

app/views/appointments/new.js.erb
<% unless @doctorslot.present? %>
  $(".flash").innerHTML = "<%= escape_javascript(render 'shared/flash') %>"
<% end %>

<% if @doctorslot.present? %>
function modalStr () {
  return `
    <div class="flex items-center justify-center min-height-100vh pt-4 px-4 pb-20 text-center sm:block sm:p-0">
      <div class="fixed inset-0 transition-opacity">
        <div class="absolute inset-0 bg-gray-900 opacity-75"></div>
      </div>

      <span class="hidden sm:inline-block sm:align-middle sm:h-screen">&#8203;</span>
      <div class="inline-block align-center bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full" role="dialog" aria-modal="true" aria-labelledby="modal-headline">

        <%= form_with url: booking_appointments_path, method: 'post', class: 'bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4' do |f| %>
          <%= f.text_field :location_id, class: 'hidden', value: @location_id, readonly: true %>
          <%= f.text_field :doctor_id, class: 'hidden', value: @doctor_id, readonly: true %>
          <label>Doctor</label>
          <input type="text" class="w-full bg-gray-100 p-2 mt-2 mb-3" value="<%= @doctorslot.doctor.full_name %>" readonly />
          <label>Patient</label>
          <input type="text" class="w-full bg-gray-100 p-2 mt-2 mb-3" value="<%= current_user.name %>" readonly />
          <%= f.label :slot_number, "Select Slot" %>
          <%= f.select :slot_number, options_for_select(@available_slots), {}, class: "w-full bg-gray-100 p-2 mt-2 mb-3" %>
          <div class="py-3 text-right">
            <%= f.submit "Pay #{@doctorslot.amount_to_pay}", class: "py-2 px-4 bg-blue-500 text-white rounded hover:bg-blue-700 mr-2" %>
            <button type="button" class="py-2 px-4 bg-gray-500 text-white rounded hover:bg-gray-700" onclick="toggleModal()">Cancel</button>
          </div>
        <% end %>
        </div>
      </div>
    </div>`
}

let modal = $("#modal")
if(modal) {
  $append(modal, modalStr())
  $("#modal").classList.remove("hidden")
}

<% end %>